/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as LeistungenRouteImport } from './routes/leistungen'
import { Route as LabRouteImport } from './routes/lab'
import { Route as KonfiguratorRouteImport } from './routes/konfigurator'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as HeldentatenRouteImport } from './routes/heldentaten'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ShareTokenRouteImport } from './routes/share.$token'
import { Route as ApiPilotGeneratorRouteImport } from './routes/api/pilot-generator'
import { Route as ApiKseAgentRouteImport } from './routes/api/kse-agent'
import { Route as AdminTutorialsRouteImport } from './routes/admin/tutorials'
import { Route as AdminMediaRouteImport } from './routes/admin/media'
import { Route as AdminInstagramRouteImport } from './routes/admin/instagram'
import { Route as AdminChatbotRouteImport } from './routes/admin/chatbot'
import { Route as ApiPublicMediaSplatRouteImport } from './routes/api/public/media.$'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const LeistungenRoute = LeistungenRouteImport.update({
  id: '/leistungen',
  path: '/leistungen',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const KonfiguratorRoute = KonfiguratorRouteImport.update({
  id: '/konfigurator',
  path: '/konfigurator',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const HeldentatenRoute = HeldentatenRouteImport.update({
  id: '/heldentaten',
  path: '/heldentaten',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPilotGeneratorRoute = ApiPilotGeneratorRouteImport.update({
  id: '/api/pilot-generator',
  path: '/api/pilot-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKseAgentRoute = ApiKseAgentRouteImport.update({
  id: '/api/kse-agent',
  path: '/api/kse-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTutorialsRoute = AdminTutorialsRouteImport.update({
  id: '/tutorials',
  path: '/tutorials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInstagramRoute = AdminInstagramRouteImport.update({
  id: '/instagram',
  path: '/instagram',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChatbotRoute = AdminChatbotRouteImport.update({
  id: '/chatbot',
  path: '/chatbot',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicMediaSplatRoute = ApiPublicMediaSplatRouteImport.update({
  id: '/api/public/media/$',
  path: '/api/public/media/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/datenschutz': typeof DatenschutzRoute
  '/heldentaten': typeof HeldentatenRoute
  '/impressum': typeof ImpressumRoute
  '/konfigurator': typeof KonfiguratorRoute
  '/lab': typeof LabRoute
  '/leistungen': typeof LeistungenRoute
  '/team': typeof TeamRoute
  '/admin/chatbot': typeof AdminChatbotRoute
  '/admin/instagram': typeof AdminInstagramRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/tutorials': typeof AdminTutorialsRoute
  '/api/kse-agent': typeof ApiKseAgentRoute
  '/api/pilot-generator': typeof ApiPilotGeneratorRoute
  '/share/$token': typeof ShareTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/datenschutz': typeof DatenschutzRoute
  '/heldentaten': typeof HeldentatenRoute
  '/impressum': typeof ImpressumRoute
  '/konfigurator': typeof KonfiguratorRoute
  '/lab': typeof LabRoute
  '/leistungen': typeof LeistungenRoute
  '/team': typeof TeamRoute
  '/admin/chatbot': typeof AdminChatbotRoute
  '/admin/instagram': typeof AdminInstagramRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/tutorials': typeof AdminTutorialsRoute
  '/api/kse-agent': typeof ApiKseAgentRoute
  '/api/pilot-generator': typeof ApiPilotGeneratorRoute
  '/share/$token': typeof ShareTokenRoute
  '/admin': typeof AdminIndexRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/datenschutz': typeof DatenschutzRoute
  '/heldentaten': typeof HeldentatenRoute
  '/impressum': typeof ImpressumRoute
  '/konfigurator': typeof KonfiguratorRoute
  '/lab': typeof LabRoute
  '/leistungen': typeof LeistungenRoute
  '/team': typeof TeamRoute
  '/admin/chatbot': typeof AdminChatbotRoute
  '/admin/instagram': typeof AdminInstagramRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/tutorials': typeof AdminTutorialsRoute
  '/api/kse-agent': typeof ApiKseAgentRoute
  '/api/pilot-generator': typeof ApiPilotGeneratorRoute
  '/share/$token': typeof ShareTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/datenschutz'
    | '/heldentaten'
    | '/impressum'
    | '/konfigurator'
    | '/lab'
    | '/leistungen'
    | '/team'
    | '/admin/chatbot'
    | '/admin/instagram'
    | '/admin/media'
    | '/admin/tutorials'
    | '/api/kse-agent'
    | '/api/pilot-generator'
    | '/share/$token'
    | '/admin/'
    | '/api/public/media/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/datenschutz'
    | '/heldentaten'
    | '/impressum'
    | '/konfigurator'
    | '/lab'
    | '/leistungen'
    | '/team'
    | '/admin/chatbot'
    | '/admin/instagram'
    | '/admin/media'
    | '/admin/tutorials'
    | '/api/kse-agent'
    | '/api/pilot-generator'
    | '/share/$token'
    | '/admin'
    | '/api/public/media/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/datenschutz'
    | '/heldentaten'
    | '/impressum'
    | '/konfigurator'
    | '/lab'
    | '/leistungen'
    | '/team'
    | '/admin/chatbot'
    | '/admin/instagram'
    | '/admin/media'
    | '/admin/tutorials'
    | '/api/kse-agent'
    | '/api/pilot-generator'
    | '/share/$token'
    | '/admin/'
    | '/api/public/media/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  DatenschutzRoute: typeof DatenschutzRoute
  HeldentatenRoute: typeof HeldentatenRoute
  ImpressumRoute: typeof ImpressumRoute
  KonfiguratorRoute: typeof KonfiguratorRoute
  LabRoute: typeof LabRoute
  LeistungenRoute: typeof LeistungenRoute
  TeamRoute: typeof TeamRoute
  ApiKseAgentRoute: typeof ApiKseAgentRoute
  ApiPilotGeneratorRoute: typeof ApiPilotGeneratorRoute
  ShareTokenRoute: typeof ShareTokenRoute
  ApiPublicMediaSplatRoute: typeof ApiPublicMediaSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen': {
      id: '/leistungen'
      path: '/leistungen'
      fullPath: '/leistungen'
      preLoaderRoute: typeof LeistungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/konfigurator': {
      id: '/konfigurator'
      path: '/konfigurator'
      fullPath: '/konfigurator'
      preLoaderRoute: typeof KonfiguratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heldentaten': {
      id: '/heldentaten'
      path: '/heldentaten'
      fullPath: '/heldentaten'
      preLoaderRoute: typeof HeldentatenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pilot-generator': {
      id: '/api/pilot-generator'
      path: '/api/pilot-generator'
      fullPath: '/api/pilot-generator'
      preLoaderRoute: typeof ApiPilotGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kse-agent': {
      id: '/api/kse-agent'
      path: '/api/kse-agent'
      fullPath: '/api/kse-agent'
      preLoaderRoute: typeof ApiKseAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tutorials': {
      id: '/admin/tutorials'
      path: '/tutorials'
      fullPath: '/admin/tutorials'
      preLoaderRoute: typeof AdminTutorialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/instagram': {
      id: '/admin/instagram'
      path: '/instagram'
      fullPath: '/admin/instagram'
      preLoaderRoute: typeof AdminInstagramRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/chatbot': {
      id: '/admin/chatbot'
      path: '/chatbot'
      fullPath: '/admin/chatbot'
      preLoaderRoute: typeof AdminChatbotRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/media/$': {
      id: '/api/public/media/$'
      path: '/api/public/media/$'
      fullPath: '/api/public/media/$'
      preLoaderRoute: typeof ApiPublicMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminChatbotRoute: typeof AdminChatbotRoute
  AdminInstagramRoute: typeof AdminInstagramRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminTutorialsRoute: typeof AdminTutorialsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminChatbotRoute: AdminChatbotRoute,
  AdminInstagramRoute: AdminInstagramRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminTutorialsRoute: AdminTutorialsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  DatenschutzRoute: DatenschutzRoute,
  HeldentatenRoute: HeldentatenRoute,
  ImpressumRoute: ImpressumRoute,
  KonfiguratorRoute: KonfiguratorRoute,
  LabRoute: LabRoute,
  LeistungenRoute: LeistungenRoute,
  TeamRoute: TeamRoute,
  ApiKseAgentRoute: ApiKseAgentRoute,
  ApiPilotGeneratorRoute: ApiPilotGeneratorRoute,
  ShareTokenRoute: ShareTokenRoute,
  ApiPublicMediaSplatRoute: ApiPublicMediaSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
